[package]
authors.workspace = true
edition.workspace = true
license.workspace = true
name = "rxec-core"
version.workspace = true

[dependencies]
pin-project.workspace = true
placid.workspace = true
spin.workspace = true
tsum.workspace = true
